#!/bin/bash
set -euo pipefail

# ML Training Server - Environment File Generator
# Generates docker/.env from config.sh for Docker Compose

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/../config.sh"
ENV_FILE="${SCRIPT_DIR}/../docker/.env"

# Load configuration
if [[ ! -f "${CONFIG_FILE}" ]]; then
    echo "ERROR: Configuration file not found: ${CONFIG_FILE}"
    echo "Please create config.sh from config.sh.example and edit it."
    exit 1
fi

source "${CONFIG_FILE}"

echo "=== Generating docker/.env from config.sh ==="
echo ""

# Check for default passwords
WARNINGS=0
if [[ "${GRAFANA_ADMIN_PASSWORD}" == "changeme_secure_password" ]]; then
    echo "⚠ WARNING: GRAFANA_ADMIN_PASSWORD is still set to default value"
    echo "  Please change it in config.sh for security"
    WARNINGS=$((WARNINGS + 1))
fi

if [[ "${USER_DEFAULT_PASSWORD}" == "changeme_default_password" ]]; then
    echo "⚠ WARNING: USER_DEFAULT_PASSWORD is still set to default value"
    echo "  Please change it in config.sh for security"
    WARNINGS=$((WARNINGS + 1))
fi

# Generate .env file
cat > "${ENV_FILE}" << 'HEADER'
# ML Training Server - Docker Compose Environment Variables
# AUTO-GENERATED from config.sh - DO NOT EDIT THIS FILE DIRECTLY!
# Edit config.sh instead and re-run: ./scripts/generate-env.sh

HEADER

# Add Grafana password
echo "# Grafana" >> "${ENV_FILE}"
echo "GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}" >> "${ENV_FILE}"
echo "" >> "${ENV_FILE}"

# Add per-user passwords
echo "# Per-user passwords (for SSH, VNC, RDP, web desktop, etc.)" >> "${ENV_FILE}"
USER_ARRAY=(${USERS})
for username in "${USER_ARRAY[@]}"; do
    # Convert username to uppercase for variable name
    USERNAME_UPPER=$(echo "${username}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')

    # Check if there's a per-user password override
    USER_PASSWORD_VAR="USER_${USERNAME_UPPER}_PASSWORD"
    if [[ -n "${!USER_PASSWORD_VAR:-}" ]]; then
        # Use the per-user override
        echo "USER_${USERNAME_UPPER}_PASSWORD=${!USER_PASSWORD_VAR}" >> "${ENV_FILE}"
    else
        # Use the default password
        echo "USER_${USERNAME_UPPER}_PASSWORD=${USER_DEFAULT_PASSWORD}" >> "${ENV_FILE}"
    fi
done
echo "" >> "${ENV_FILE}"

# Add domain and mount point
echo "# Domain for Cloudflare Tunnel" >> "${ENV_FILE}"
echo "DOMAIN=${DOMAIN}" >> "${ENV_FILE}"
echo "" >> "${ENV_FILE}"

echo "# Mount point for storage" >> "${ENV_FILE}"
echo "MOUNT_POINT=${MOUNT_POINT}" >> "${ENV_FILE}"
echo "" >> "${ENV_FILE}"

echo "✅ Generated: ${ENV_FILE}"
echo ""
echo "Contents:"
echo "  - GRAFANA_ADMIN_PASSWORD"
for username in "${USER_ARRAY[@]}"; do
    USERNAME_UPPER=$(echo "${username}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
    echo "  - USER_${USERNAME_UPPER}_PASSWORD"
done
echo "  - DOMAIN (${DOMAIN})"
echo "  - MOUNT_POINT (${MOUNT_POINT})"
echo ""

if [[ ${WARNINGS} -gt 0 ]]; then
    echo "⚠️  ${WARNINGS} warning(s) found. Please review and update config.sh."
    exit 0
else
    echo "✅ All done!"
    exit 0
fi
